### ISSUE TITLE
Add Sonic Pi ide

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#313]

**Comment by asokero** [comment]
http://sonic-pi.net/
https://launchpad.net/~sonic-pi/+archive/ubuntu/ppa

**Comment by asokero** [comment]
Trying to get this running on Ubuntu 14.04 might be a bit of a mess for an ordinary student/user. Currently I've got it running by 

1. running `pasuspender -- qjackctl`
2. changing the sound device from the qjackctl > Settings > Interface > right arrow
3. and then launching `sonic-pi`

Still sometimes Sonic Pi begins to report about: 
```
=> Studio: Attempting to reboot again in 10s

=> Studio: Forcing shutdown of any running server

=> Studio: Error shutting down server:  closed stream, ["/usr/lib/sonic-pi/server/sonicpi/lib/sonicpi/osc/udp_server.rb:63:in `close'", "/usr/lib/sonic-pi/server/sonicpi/lib/sonicpi/osc/udp_server.rb:63:in `stop'", "/usr/lib/sonic-pi/server/sonicpi/lib/sonicpi/scsynthexternal.rb:75:in `shutdown'", "/usr/lib/sonic-pi/server/sonicpi/lib/sonicpi/server.rb:452:in `shutdown'", "/usr/lib/sonic-pi/server/sonicpi/lib/sonicpi/studio.rb:66:in `rescue in block (2 levels) in initialize'", "/usr/lib/sonic-pi/server/sonicpi/lib/sonicpi/studio.rb:57:in `block (2 levels) in initialize'", "/usr/lib/sonic-pi/server/sonicpi/lib/sonicpi/studio.rb:50:in `loop'", "/usr/lib/sonic-pi/server/sonicpi/lib/sonicpi/studio.rb:50:in `block in initialize'"]

=> Studio: Rebooting server. Please wait...

=> Studio: Error rebooting server:  closed stream, ["/usr/lib/sonic-pi/server/sonicpi/lib/sonicpi/osc/udp_server.rb:63:in `close'", "/usr/lib/sonic-pi/server/sonicpi/lib/sonicpi/osc/udp_server.rb:63:in `stop'", "/usr/lib/sonic-pi/server/sonicpi/lib/sonicpi/scsynthexternal.rb:75:in `shutdown'", "/usr/lib/sonic-pi/server/sonicpi/lib/sonicpi/server.rb:452:in `shutdown'", "/usr/lib/sonic-pi/server/sonicpi/lib/sonicpi/studio.rb:339:in `server_reboot'", "/usr/lib/sonic-pi/server/sonicpi/lib/sonicpi/studio.rb:58:in `block (2 levels) in initialize'", "/usr/lib/sonic-pi/server/sonicpi/lib/sonicpi/studio.rb:50:in `loop'", "/usr/lib/sonic-pi/server/sonicpi/lib/sonicpi/studio.rb:50:in `block in initialize'"]

```
